Develop
pribytkovskiy/codebreaker pull request #1
Opened 2018-11-29 14:22 UTC by pribytkovskiy

2018-12-13 17:42 UTC, dzemlianoi-double commented on .rspec_status
> +example_id                       | status  | run_time        |
remove please

2018-12-13 17:42 UTC, dzemlianoi-double commented on Gemfile
> +gem 'i18n'
group

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +require './auto_load.rb'
move to start file

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +    HELL = { level: 'hell', attempts: 5, hints: 1 }.freeze
1 constant

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +        when I18n.t(:start_command)
constant

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +        when I18n.t(:exit_command)
when I18n.t(:exit_command) then return exit_message

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +        when I18n.t(:stats_command)
try to use one line when

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +        when I18n.t(:easy_level)
use constant as a base for chose level

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +      difficulty
use prefixes in method naming

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +      while @game.exit? != true
while !@game.exit?

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +        when /\A[1-6]{4}\Z/
move to game

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +      check_name_for_string(@name)
try to rethink vaidations

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/console.rb
> +      exit unless gets.chomp == 'y'
exit if gets.chomp != 'y'

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/errors.rb
> +      super('Name length between 3 - 20 chars')
constantize it

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/game.rb
> +require 'i18n'
move to autoload

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/game.rb
> +      @exit = false
mb finished

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/game.rb
> +    def statistik
statistik -> statistics

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/game.rb
> +      (1..4).map { rand(1..6) }
const

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/game.rb
> +      @secret_code = random
attr_reader

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/storage.rb
> +          puts I18n.t(:no_file)
move to console

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/storage.rb
> +          f.puts name, game.statistik, Time.now
move to console

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/validation.rb
> +    raise NameLengthError unless name.length.between?(3, 20)
constant

2018-12-13 17:42 UTC, dzemlianoi-double commented on modules/validation.rb
> +  def check_name_for_string(name)
chechable + class for check

2018-12-13 17:42 UTC, dzemlianoi-double commented on spec/console_spec.rb
> +require 'spec_helper'
try to redone it

2019-01-02 21:28 UTC, Svatok requested changes
Fix specs https://circleci.com/gh/pribytkovskiy/codebreaker/14
Also your circleci running only 9 specs, please fix this

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +        return @game.difficulty(DIFFICULTIES[input_as_key.to_sym]) if DIFFICULTIES.key?(input_as_key)
Why do you symbolize input in second time?

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +        return @game.difficulty(DIFFICULTIES[input_as_key.to_sym]) if DIFFICULTIES.key?(input_as_key)
`return` and `if DIFFICULTIES.key?(input_as_key)` are redundant

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +      save_statisctics(@name, @game)
`@name, @game` - use attr_reader

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +      until @game.end_game?
without `@`

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +      exit if gets.chomp != 'y'
`unless gets.chomp == 'y'`

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +      if File.file?(PATH_STATS.to_s)
`to_s` is redundant

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +        f.puts '------------------------------'
to i18 or to constant

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +    def validate
rename to `validate_name`

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +    def validate
rename to `validate_name`

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +      @errors << I18n.t('wrong_class', obj: @name, klass: String) unless check_for_class?(@name, String)
`validate_class` instead of `check_for_class`

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +      @errors << I18n.t('length_error') unless check_for_length?(@name)
`validate_length` instead of `check_for_length`

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +    def statisctics
Move to separate class. (something like `Database`)

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +    def save_statisctics(name, game)
Move to separate class. (something like `Database`)

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +      @end_game
if you use `attr_reader` then `@` is redundant

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +      "Status: #{@status}, level: #{@level}, secret code: #{@secret_code}, attempts total: #{@total_attempts},
without `@`

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +      "Status: #{@status}, level: #{@level}, secret code: #{@secret_code}, attempts total: #{@total_attempts},
Use i18

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +      @code = code.split('').map(&:to_i)
without `('')`

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +      @total_attempts = @attempts = difficulty[:attempts]
```ruby
@difficulty = difficulty
@attempts = difficulty[:attempts]
@hints = difficulty[:hints]
```

And then use `difficulty[:attempts]` instead of @total_attempts. (with `@total_hints` and `@level` the same)

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +    def mark
Move this to separate service

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +      return exit_with_status(I18n.t(:no_attempts)) if @attempts.zero?
`return` is redundant

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +      return exit_with_status(I18n.t(:win)) if @code == @secret_code
`return` is redundant

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +      return exit_with_status(I18n.t(:win)) if @code == @secret_code
maybe `exit_with_message`?

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +    attr_reader :game, :errors
`:errors` move to ValidatableEntity

2019-01-02 21:28 UTC, Svatok commented on modules/game.rb
> +    def end_game?
I think this is redundant method.

2019-01-02 21:28 UTC, Svatok commented on modules/validatable_entity.rb
> +  def valid?
From where you copy this code? You do not use this method anywhere in code.

2019-01-02 21:28 UTC, Svatok commented on modules/validatable_entity.rb
> +class ValidatableEntity
Сombine this class with `module Validation` and use only module

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +      exit if gets.chomp != 'y'
`y` to constant

2019-01-02 21:28 UTC, Svatok commented on spec/console_spec.rb
> +    let(:name) { 'Di' }
ffaker

2019-01-02 21:28 UTC, Svatok commented on spec/console_spec.rb
> +    let(:code) { '1234' }
ffaker

2019-01-02 21:28 UTC, Svatok commented on spec/console_spec.rb
> +    let(:rules) { 'Game Rules' }
ffaker

2019-01-02 21:28 UTC, Svatok commented on spec/console_spec.rb
> +    let(:yes) { 'y' }
from constant

2019-01-02 21:28 UTC, Svatok commented on .rspec_status
> +example_id                               | status  | run_time        |
to `gitignore`

2019-01-02 21:28 UTC, Svatok commented on modules/console.rb
> +    DIFFICULTIES = { easy: { hints: 2, attempts: 15, level: 'easy' },
```ruby
DIFFICULTIES = {
...
}.freeze
```

2019-01-09 22:29 UTC, Svatok requested changes

2019-01-09 22:29 UTC, Svatok commented on .rspec_status
> +example_id                               | status | run_time        |
Remove this file from git

2019-01-09 22:29 UTC, Svatok commented on modules/console.rb
> +        puts I18n.t(:unexpected_level) unless DIFFICULTIES.key?(input_as_key)
```ruby
        return game.difficulty(DIFFICULTIES[input_as_key]) if DIFFICULTIES.key?(input_as_key)
        puts I18n.t(:unexpected_level)
```

2019-01-09 22:29 UTC, Svatok commented on modules/console.rb
> +      return unless gets.chomp == 'y'
constant

2019-01-09 22:29 UTC, Svatok commented on modules/console.rb
> +    def statisctics
!

2019-01-09 22:29 UTC, Svatok commented on modules/console.rb
> +        f.puts '------------------------------'
!

2019-01-09 22:29 UTC, Svatok commented on modules/console.rb
> +    def validate
!

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      @total_attempts = @attempts = difficulty[:attempts]
!

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +    def end_game?
!

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      @end_game
!

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      "Status: #{@status}, level: #{@level}, secret code: #{@secret_code}, attempts total: #{@total_attempts},
!

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      @code = code.split('').map(&:to_i)
!

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      @hint_array ||= @secret_code.shuffle
@secret_code without `@`

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      return I18n.t(:no_hint) if @hints.zero?
attr_reader

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      return exit_with_status(I18n.t(:win)) if @code == @secret_code
!

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      return exit_with_status(I18n.t(:win)) if @code == @secret_code
All messages move to console

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      return exit_with_status(I18n.t(:no_attempts)) if @attempts.zero?
!

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +      return exit_with_status(I18n.t(:no_attempts)) if @attempts.zero?
All messages move to console

2019-01-09 22:29 UTC, Svatok commented on modules/game.rb
> +    def mark
!

2019-01-09 22:29 UTC, Svatok commented on modules/validatable_entity.rb
> +  def valid?
!!!!!!!!!!

2019-01-09 22:29 UTC, Svatok commented on spec/console_spec.rb
> +    let(:rules) { 'Game Rules' }
!

2019-01-09 22:31 UTC, Svatok reviewed
Where i wrote `!` please fix my comments from previous review.

2019-01-09 22:52 UTC, Svatok commented on modules/console.rb
> +    def receive_game_code # rubocop:disable Metrics/AbcSize
Please without rubocop disabling. For example:
```ruby
    def play_game
      receive_difficulty
      receive_name
      game_process
      save_statisctics
      play_again
    end

    def game_process
      puts I18n.t(:enter_code)
      loop do
        return if game.end_game?
        receive_code(gets.chomp)
      end
    end

    def receive_code(input)
      return puts I18n.t(:unexpected_code) unless COMMANDS[:hint] == input || code?(input)
      puts code?(input) ? game.guess(code) : game.hint
    end

    def code?(input)
      input =~ REG_EXP_FOR_CODE
    end
```

2019-01-14 09:47 UTC, Svatok commented on modules/storage.rb
> +        if File.file?(PATH_STATS)
```ruby
File.file?(PATH_STATS) ? File.open(PATH_STATS, &:read) : STATUS[:no_file]
```

2019-01-14 09:47 UTC, Svatok commented on modules/mark.rb
> +      def mark_plus(input_code, secret_code)
Add def call(input_code, secret_code):
```ruby
      def call(input_code, secret_code)
        @array_code = input_code.dup
        @array_secret_code = secret_code.dup
        mark_plus
        mark_minus
      end
```

2019-01-14 09:47 UTC, Svatok commented on modules/game.rb
> +      Codebreaker::Mark.mark_plus(array_input_code, secret_code)
Codebreaker::Mark.call(array_input_code, secret_code)

2019-01-14 09:47 UTC, Svatok commented on modules/mark.rb
> +      def mark_plus(input_code, secret_code)
```ruby
      def mark_plus
        @answer = array_code.map.with_index do |guess_number, i|
          next if guess_number != array_secret_code[i]

          array_secret_code[i], array_code[i] = nil
          '+'
        end
        array_code.compact!
        array_secret_code.compact!
      end
```

2019-01-14 09:47 UTC, Svatok commented on modules/mark.rb
> +      def mark_minus(array_code, array_secret_code)
```ruby
      def mark_minus
        array_code.each do |code_number|
          index = array_secret_code.index(code_number)
          next unless index

          array_secret_code.delete_at(index)
          @answer << '-'
        end
        @answer.join
      end
```

2019-01-14 09:47 UTC, Svatok commented on spec/game_spec.rb
> +      context 'when #mark' do
Please add more tests for mark and move this specs to mark_spec.rb

2019-01-14 15:20 UTC, Svatok approved these changes

2019-01-15 15:09 UTC, merged